extensions/sonarqube/overview.md
@henryju I've added a notice for users on old TFS versions.
I also updated the doc on https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS:
* to specify the compatibility for each version
* to tell how to install older versions of the extension and redirect to the correct doc page
If I'm not mistaken, the only thing that remains on your side is:
* to update the manifest in order to set the right compatibility for the upcoming 4.0.2 release
* to read and validate the changes I made (in this PR and on the doc)
=> VSTS-135 - Task fails to install on TFS earlier than 2017 Update 2

extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/tasks/publish/new/task.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/tasks/publish/new/task.json
I've incremented the minor versions of all of tasks, except for the "old cli" task which has not changed because the version of the embedded CLI has not changed.
It wasn't strictly necessary to update the versions of the "publish" tasks, but it's less confusing to have the "new" tasks at the same version number.
=> Update task versions for release of SC 1.2.0 and SQ 4.2.0

.gitignore, common/ts/sonarqube/Task.ts
Related issue: https://community.sonarsource.com/t/sonar-scanner-vsts-provide-error-message-when-sq-task-failed/6556
Currently when Publish Quality Gate Result task failed, we get not informative message that task is failed.
To get more details user have to login in SonarCloud account for investigation and read error message from "Background tasks". For example:
Actual error:
```
Error Details
#11111' is not a valid branch name. It can only contain 'A-Z', 'a-z', '0-9', '-', '_', '.', and '/')
```
In Azure DevOps (VSTS), I see only this not informative message:
```
##[section]Starting: Publish Quality Gate Result
==============================================================================
Task         : Publish Quality Gate Result
Description  : Publish SonarCloud's Quality Gate result …
```
=> Provide error message when SQ task failed

common/ts/__tests__/prepare-task-test.ts, common/ts/prepare-task.ts, common/ts/sonarqube/Scanner.ts, common/ts/sonarqube/__tests__/Scanner-test.ts
This issue was because the call to sonar-scanner cli is done through a wrapper (.bat or not), using SONAR_SCANNER_OPTS environment variable to fill arguments to pass to that CLI. This env variable was never written in the extension, so now it's done.
=> VSTS-171 - Write SONAR_SCANNER_OPTS env variable if standalone scanner is selected in the Prepare Analysis Task configuration.

common/ts/__tests__/publish-task-test.ts, common/ts/prepare-task.ts, common/ts/publish-task.ts, common/ts/sonarqube/TaskReport.ts, common/ts/sonarqube/__tests__/TaskReport-test.ts, extensions/sonarcloud/overview.md
newest location of report-task.txt is now dedidated to either SonarCloud or SQ >= 7.2 + Added fallback research to previous folders in case of SQ < 7.2.
=> VSTS-213 - Report-task.txt new location improvement

common/ts/publish-task.ts
Inform users when the publish task did not actually do anything by logging a warning.
=> Log a warning when no analysis was found

common/ts/prepare-task.ts
Adds support for branch detection in the prepare analysis task when the repository provider is GitHub Enterprise.
=> Support branch detection for GitHub Enterprise

README.md, package.json
* The simple npm install wasn't working to build after, I had to do a full npm install thanks to the cirrus script
* I was using an older of npm which what changing all the package-lock files, so I added the requirement to have npm v8 or upper in the package.json file
=> Update readme and npm required version

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
We need to bump the version of the S4NET before the release of SQ 9.9 LTS for Incremental PR Analysis to work for .NET projects.
=> VSTS-297 Bump Scanner for .NET to v5.11.0.60783

commonv5/ts/__tests__/prepare-task-test.ts, commonv5/ts/prepare-task.ts, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-298 fix version comparison

commonv5/ts/sonarqube/TaskReport.ts, commonv5/ts/sonarqube/__tests__/TaskReport-test.ts
=> VSTS-301 Fix semver check for compatibility with SQ >= 10.0

commonv5/ts/sonarqube/Endpoint.ts, commonv5/ts/sonarqube/__tests__/Endpoint-test.ts, extensions/sonarcloud/tasks/prepare/v1/task.json
Extension version and analyze task bumps happened in the VSTS-311 PR that was merged earlier today. 
=> VSTS-310 Use sonar.token instead of login for SonarCloud

config/paths.js, config/utils.js, gulpfile.js
Minor code reorganizations and comments to ease understanding of what is happening during the build process, including with downloading msbuild scanners and extracting cli scanner. There _should not_ be any functional changes.
- Moved utilities out of gulpfile into config/utils
- Renamed some misleading gulp task names
- Added comments around code that downloads and extract scanners & reorder code semantically (per scanner kind)
=> [NO-JIRA] Refactor build process

commonv5/ts/__tests__/prepare-task-test.ts, commonv5/ts/prepare-task.ts
This PR removes a condition where we don't set `sonar.branch.name` for the default branch. ([ticket](https://sonarsource.atlassian.net/browse/VSTS-317)) 
I followed the next steps to test it (SC and SQ Next):
1. Run branch analysis for default branch (main)
2. Run analysis for secondary branch
3. Changed some code in main and run new analysis for default branch
=> VSTS-317 Prepare task shows redundant warning when sonar.branch.name is provided in extra params

commonv5/ts/__tests__/prepare-task-test.ts, commonv5/ts/helpers/request.ts, commonv5/ts/prepare-task.ts, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
This PR reverts changes being done to `sonar.branch.name`.  However, to not pollute users with the permission warning, I use debug instead.
=> VSTS-320 Fix populating of sonar.branch.name in Community edition

commonv5/ts/helpers/request.ts, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
As part of a recent [dependency upgrade sprint](https://github.com/SonarSource/sonar-scanner-vsts/pull/291), the obsolete request library was changed to axios. 
Axios is sending, by default, is sending its user agent to SonarQube instance. While this is not an issue for SQ, some specific and custom setups with reverse proxy may reject requests from Azure CI before they reach the SQ instance, based on this HTTP header  `User-Agent: axios/0.27.2`.
This PR resets this user agent so that it is not sent (corresponding to the behavior before `5.16.0`).
=> [NO-JIRA] Fix axios sending custom user agent to SonarQube instance

.gitignore, config/config.js, config/utils.js, gulpfile.js
This PR eases including custom scanner archives in extension test builds. Before this PR, it was only possible to download scanners from the URL passed in `config.js`. It is now possible to use a relative path to include local scanner archives in the extension build.
Steps:
1. Modify `config/config.js` and set `scannersLocation = './'`
2. Ensure you have scanners named `sonar-scanner-msbuild-${msBuildVersion}-net46.zip` and `sonar-scanner-msbuild-${msBuildVersion}-netcoreapp3.0.zip` in the extension/repository root folder
3. Build the extension as usual, eg `npm run build`
The extension will be built with the custom scanners that you specified. 
The previous behavior is left intact. The default behavior is still to fetch the specified release from GitHub.
=> VSTS-328 Allow local scanner archives to be used at build time

common/ts/sonarqube/__tests__/__snapshots__/Analysis-test.ts.snap, commonv5/ts/sonarqube/__tests__/__snapshots__/Analysis-test.ts.snap, package-lock.json, package.json
Only jest and jest-ts libraries were using babel/traverse 7.15. Updating these 2 updated babel/traverse to >7.23 which is not vulnerable.
=> VSTS-326 Update jest to use non vulnerable babel/traverse package

common/ts/sonarqube/Scanner.ts, commonv5/ts/__tests__/analyze-task-test.ts, commonv5/ts/__tests__/publish-task-test.ts, commonv5/ts/analyze-task.ts, commonv5/ts/helpers/__tests__/java-version-resolver-test.ts, commonv5/ts/helpers/__tests__/utils-test.ts, commonv5/ts/helpers/constants.ts, commonv5/ts/helpers/java-version-resolver.ts, commonv5/ts/helpers/utils.ts, commonv5/ts/prepare-task.ts, commonv5/ts/publish-task.ts, commonv5/ts/sonarqube/Analysis.ts, commonv5/ts/sonarqube/Endpoint.ts, commonv5/ts/sonarqube/Scanner.ts, commonv5/ts/sonarqube/TaskReport.ts, commonv5/ts/sonarqube/__tests__/Endpoint-test.ts, commonv5/ts/sonarqube/__tests__/TaskReport-test.ts
**VSTS-221 Document logic to decide whether we are on the main branch or not**
In the end, I decided to keep the same logic than currently. It is not worth it IMO to take risk to break Developer+ instances to have Community Edition supporting main branch with other names than `master`
The current behavior is:
- For azure repos, we send the property if the analyzed branch is not the default branch. If the Web API can not be reached, the fallback is to send the property only if the analyzed branch is not `master`.
- For SVN, we send the property if the analyzed branch is not `trunk`. 
- For other providers we send the property if and only if the branch is not `master`
This PR focuses on code quality and documentation to make the current behavior clear
____
**VSTS-309 Fail fast if required …
=> VSTS-221 VSTS-308 Document logic to decide whether we are on the main branch or not & multistage pipeline and major task versions

common/ts/helpers/request.ts, common/ts/package-lock.json, common/ts/package.json, common/ts/sonarqube/Analysis.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/Metrics.ts, common/ts/sonarqube/Task.ts, common/ts/sonarqube/__tests__/Analysis-test.ts, commonv5/ts/package-lock.json, commonv5/ts/package.json, commonv5/ts/sonarqube/Endpoint.ts
- Completely drop axios in favor of node-fetch in V4 of the extension (will not be released)
- Drop `proxy-agent` in favor of manually instantiating `http-proxy-agent` or `https-proxy-agent` depending on endpoint url
=> VSTS-324 Drop V4 axios in favor of node-fetch & Fix mend vm2 vulnerability

extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
Bump version of the SQ extension and its V5 tasks
We will not be releasing the SC extension so that we do not disrupt with your plans, in case work needs to be done after the release. We will extend functional validation related to our hardening sprint to SC to avoid any surprise when you do the SC release.
@quentin-chevrin-sonarsource @alexandre-holzhey-sonarsource @ivan-murenko-sonarsource
=> [NO-JIRA] Bump SonarQube and V5 task versions

commonv5/ts/helpers/constants.ts, commonv5/ts/prepare-task.ts, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
This is an attempt at fixing [this community thread](https://community.sonarsource.com/t/ado-extension-broken/104618), It is the only functional change from `5.17.2`
Although assuming that we are not on the default branch is safer for Commercial Editions, because they will not fail when the branch is set, not setting it in that particular case is consistent with the behavior of `5.17.2`, so that can technically be considered a breaking change in case a user:
- is using the Community Edition
- is not using "master" as his main branch
- has a code provider not recognized by our code
We can change this when we upgrade tasks to a next major version
=> [NO-JIRA] Assume default branch when no provider is detected

.cirrus/Dockerfile, package.json
And please ensure your pull request adheres to the following guidelines: 
Next now requires java 17 to run the scanners. The scanner-npm dependency needs to be updated to have the embedded jre updated to 17. I also updated the runtime of the docker build to be aligned with other repositories.
=> NO-JIRA update base image for j17 and update scanner-npm

.cirrus/Dockerfile
The way we install NodeJS in the image used during build is deprecated. We should update the image to properly install NodeJS and ensure we use NodeJS 18. This may fix the nightly build which fails because of NodeJS version mismatch (expects 16+, has 14).
This was caused by bumping `sonar-scanner-npm` from `3.0.0` to `3.3.0` because `3.1.0` includes `sonar-scanner-cli@5`
=> VSTS-343 Remove deprecated NodeJS installation in build Dockerfile

commonv5/ts/sonarqube/HtmlAnalysisReport.ts
The goal with this PR is to as close as possible to the expected result from UX mockup with the data we already have. Only available measures are included in the summary when the QG passes now. More information can be found in our internal VSTS ticket.
=> VSTS-347 Show available measures when they are available through QG conditions even when QG passes

commonv5/ts/__tests__/analyze-task-test.ts, commonv5/ts/__tests__/publish-task-test.ts, commonv5/ts/analyze-task.ts, commonv5/ts/helpers/__tests__/utils-test.ts, commonv5/ts/helpers/api.ts, commonv5/ts/helpers/constants.ts, commonv5/ts/helpers/html.ts, commonv5/ts/helpers/utils.ts, commonv5/ts/prepare-task.ts, commonv5/ts/publish-task.ts, commonv5/ts/sonarqube/HtmlAnalysisReport.ts, commonv5/ts/sonarqube/Task.ts, commonv5/ts/sonarqube/__tests__/HtmlAnalysisReport-test.ts, commonv5/ts/sonarqube/__tests__/__snapshots__/HtmlAnalysisReport-test.ts.snap, commonv5/ts/sonarqube/types.ts
This PR tries and fetch measures in the list `[new_violations, pull_request_fixed_issues, new_accepted_issues, new_security_hotspots, new_coverage, new_duplicated_lines_density]` respecting this logic:
- Doesn't try to show `pull_request_fixed_issues` when not on pull requests
- Doesn't show coverage or duplication data if there's none to show
- Doesn't try to fetch measures if there are not listed in available metrics (`/api/metrics/search`)
- If the metric exists but could not get the measure (possible, see next paragraph), tries to get the measure value from the QG condition
- Gracefully degrades the UI when some measures are not available (see examples)
Known limitation: Measures will only be able to be fetched when a user token is used for the analysis. Project analysis and Global …
=> VSTS-344 VSTS-345 Show issues fixed in PR and accepted issues in build summary when possible

commonv5/ts/package-lock.json, commonv5/ts/package.json, extensions/sonarcloud/tasks/analyze/v1/package-lock.json, extensions/sonarcloud/tasks/analyze/v1/package.json, extensions/sonarcloud/tasks/prepare/v1/package-lock.json, extensions/sonarcloud/tasks/prepare/v1/package.json, extensions/sonarcloud/tasks/publish/v1/package-lock.json, extensions/sonarcloud/tasks/publish/v1/package.json, extensions/sonarqube/tasks/analyze/v4/package-lock.json, extensions/sonarqube/tasks/analyze/v4/package.json, extensions/sonarqube/tasks/analyze/v5/package-lock.json, extensions/sonarqube/tasks/analyze/v5/package.json, extensions/sonarqube/tasks/prepare/v4/package-lock.json, extensions/sonarqube/tasks/prepare/v4/package.json, extensions/sonarqube/tasks/prepare/v5/package-lock.json, extensions/sonarqube/tasks/prepare/v5/package.json, extensions/sonarqube/tasks/publish/v4/package-lock.json, extensions/sonarqube/tasks/publish/v4/package.json, extensions/sonarqube/tasks/publish/v5/package-lock.json, extensions/sonarqube/tasks/publish/v5/package.json, package-lock.json, package.json
The version of azure-pipelines-task-lib used in tasks is fixed to 4.4.0 for SQ V5 tasks and SC tasks, but was set to ^4.4.0 in SQ V4 tasks which means V4.6.0 was used. We should:
- Upgrade to 4.7.0
- Stick to the fixed-version usage and use specifically 4.7.0 for V4 tasks (instead of ^4.7.0)
=> VSTS-348 Upgrade azure pipelines task lib to V4.7.0 & Use specific version rather than auto-upgrade syntax

common/ts/package-lock.json, common/ts/package.json, common/ts/sonarqube/Scanner.ts, commonv5/ts/package-lock.json, commonv5/ts/package.json, commonv5/ts/sonarqube/Scanner.ts, extensions/sonarcloud/tasks/analyze/v1/package-lock.json, extensions/sonarcloud/tasks/analyze/v1/package.json, extensions/sonarcloud/tasks/prepare/v1/package-lock.json, extensions/sonarcloud/tasks/prepare/v1/package.json, extensions/sonarcloud/tasks/publish/v1/package-lock.json, extensions/sonarcloud/tasks/publish/v1/package.json, extensions/sonarqube/tasks/analyze/v4/package-lock.json, extensions/sonarqube/tasks/analyze/v4/package.json, extensions/sonarqube/tasks/analyze/v5/package-lock.json, extensions/sonarqube/tasks/analyze/v5/package.json, extensions/sonarqube/tasks/prepare/v4/package-lock.json, extensions/sonarqube/tasks/prepare/v4/package.json, extensions/sonarqube/tasks/prepare/v5/package-lock.json, extensions/sonarqube/tasks/prepare/v5/package.json, extensions/sonarqube/tasks/publish/v4/package-lock.json, extensions/sonarqube/tasks/publish/v4/package.json, extensions/sonarqube/tasks/publish/v5/package-lock.json, extensions/sonarqube/tasks/publish/v5/package.json, package-lock.json, package.json
After the upgrade of `azure-pipelines-task-lib` to `4.7.0`, 2 code smells were created on Next regarding `ToolRunner.exec(..)` deprecated in favor of `ToolRunner.execAsync(..)`. 
It was not detected in the pull request because it wasn't part of the changed lines
____
Also, this PR fixes the remaining Mend vulnerability that we have on `follow-redirects`. Since we specify already that NPM 8 should be used, it uses `overrides` mechanism from NPM to fix the `follow-redirects` version to the latest.
=> VSTS-348 Fix SQ code smell after azure-pipelines-task-lib upgrade

gulpfile.js
We were never using pull request analysis correctly on our Next SonarQube instance. We were actually using branch analysis instead of pull request analyses. A side effect is that we never had pull request decoration in our PRs.
This PR fixes the way we run SQ analysis in our gulp task, so we'll have PR decoration now
=> VSTS-350 Treat pull requests correctly on SonarQube Next instance

.cirrus.yml, gulpfile.js
[this commit](https://github.com/SonarSource/sonar-scanner-vsts/commit/f7102231e6a0b251fa7bd8f984ed8cb389050cd2) added PR decoration but also introduced a regression for branch builds (1), and it wasn't properly analyzing PRs because of an old bug in the gulp file (2).
(1) This PR fixes the usage of [`CIRRUS_PR`](https://cirrus-ci.org/guide/writing-tasks/#environment-variables) which was never correct. The current code assumes `CIRRUS_PR` can take values `false` or `true` but in fact, these are the actual values:
- On master branch, it's unset
- In PR: ![image](https://github.com/SonarSource/sonar-scanner-vsts/assets/31401273/fb4c934e-a666-4578-95e2-3ef27eea66bb)
(2) In PR analyses, no change was detected because the CI environment did not have the `master` branch to compare the changes …
=> VSTS-350 Fix Next SQ branch analysis and CIRRUS_PR usage

commonv5/ts/__tests__/publish-task-test.ts, commonv5/ts/helpers/__tests__/api-test.ts, commonv5/ts/helpers/api.ts, commonv5/ts/helpers/request.ts, commonv5/ts/helpers/utils.ts, commonv5/ts/publish-task.ts, commonv5/ts/sonarqube/Task.ts, commonv5/ts/sonarqube/__tests__/Task-test.ts
Here is the output in the terminal when the request fails (once):
```text
2024-01-16T12:57:37.7455381Z ##[debug][SQ] API GET: '/api/ce/task' with full URL "https://xxx.eu.ngrok.io/api/ce/task?id=AY0SWUK2VqVwuP_SOuqo" and query "{"id":"AY0SWUK2VqVwuP_SOuqo"}"
2024-01-16T12:57:37.8555253Z ##[debug][SQ] Task status:IN_PROGRESS
2024-01-16T12:57:38.8580785Z ##[debug][SQ] API GET: '/api/ce/task' with full URL "https://xxx.eu.ngrok.io/api/ce/task?id=AY0SWUK2VqVwuP_SOuqo" and query "{"id":"AY0SWUK2VqVwuP_SOuqo"}"
2024-01-16T12:57:38.9892444Z ##[debug][SQ] Task status:IN_PROGRESS
2024-01-16T12:57:39.9909318Z ##[debug][SQ] API GET: '/api/ce/task' with full URL "https://xxx.eu.ngrok.io/api/ce/task?id=AY0SWUK2VqVwuP_SOuqo" and query "{"id":"AY0SWUK2VqVwuP_SOuqo"}"
2024-01-16T12:57:40.1174809Z …
```
=> VSTS-349 Add retry mechanism during polling

extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/publish/v4/task.json, extensions/sonarqube/vss-extension.json
Follow-up on https://github.com/SonarSource/sonar-scanner-vsts/pull/346 which will let us release a new extension version fixing compatibility with V4 tasks
=> VSTS-338 Bump SQ V4 task versions

commonv5/ts/__tests__/analyze-task-test.ts, commonv5/ts/analyze-task.ts, commonv5/ts/helpers/__tests__/java-version-resolver-test.ts, commonv5/ts/helpers/constants.ts, commonv5/ts/helpers/java-version-resolver.ts, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
We can not just switch to Java 17 by default, because we would break users that do not have Java 17 installed in their agents.
Instead, we:
- Ignore the specified Java 11 if we know the server does not support it (SonarQube >= 10.4). In that case, switch to using the default JAVA_HOME.
- Add a warning message to the task when we ignore it and tell users to update the task to specify jdkversion
=> VSTS-355 Ignore specified JDK 11 if server does not support it

package-lock.json, package.json
This fixes the mend alert on the obsolete gulp 4.x. We are now forcing the specific version of `es5-ext` in dev dependencies.
=> NO-JIRA Bump es5-ext to 0.10.64 to fix obsolete gulp mend vulnerability

commonv5/ts/helpers/__tests__/java-version-resolver-test.ts, commonv5/ts/helpers/constants.ts, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/vss-extension.json
Add support to select JDK21 in analyze tasks of both the SonarCloud and SonarQube extensions. It is indeed now available in the hosted agents
through
=> VSTS-360 Add support to select JDK21 on hosted agents

config/utils.js, gulpfile.js, package-lock.json, package.json, src/common/latest/esbuild.config.js, src/common/sonarcloud-v1/esbuild.config.js, src/common/sonarqube-v4/esbuild.config.js, src/common/sonarqube-v5/esbuild.config.js
Using esbuild to inline all dependencies (and drop `node_modules` from task folders)
We need to to add a workaround [for shelljs because we can not bundle it](https://github.com/7PH/azure-devops-extension-bundler-shelljs-poc)
Size before this PR, on master branch with V1+V4+V5
```text
19M     dist/sonar-scanner-vsts-1.46.0-sonarcloud.vsix
37M     dist/sonar-scanner-vsts-5.20.0-sonarqube.vsix
```
Size after this PR
```text
3.4M    dist/sonar-scanner-vsts-1.46.0-sonarcloud.vsix
6.8M    dist/sonar-scanner-vsts-5.20.0-sonarqube.vsix
```
(After rebase with the 2 new versions, V1+V2+V4+V5+V6):
```text
5.0M    ./dist/sonar-scanner-vsts-2.0.0-sonarcloud.vsix
9.1M    ./dist/sonar-scanner-vsts-6.0.0-sonarqube.vsix
```
On my machine, before
```text
[12:24:35] Finished 'default' after 34 s
```
After …
=> VSTS-268 Bundle and tree-shake extension task code

gulpfile.js, src/common/latest/azure-pipelines-tool-lib.json, src/common/latest/helpers/constants.ts
[azure-pipelines-tool-lib requires package.json and lib.json to be present](https://github.com/microsoft/azure-pipelines-tool-lib/blob/830ec78dd0f0fe3d8aad5a82c469fe52f736b738/tool.ts#L15) but we're not bundling it with the task, this breaks the build
=> VSTS-371 Fix bundled azure-pipelines-tool-lib

src/common/latest/esbuild.config.js, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v2/task.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/tsconfig.json
[ticket](https://sonarsource.atlassian.net/browse/VSTS-376) with all the details
=> VSTS-376 Bump minimum agent version in SQ V6 & SC V2 tasks to ensure Node16 is available and transpile/bundle to Node16

src/common/latest/__tests__/prepare-task-test.ts, src/common/latest/config.ts, src/common/latest/prepare-task.ts, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json
To ensure users are, by default, using the recommended version of scanners that we specify in the latest version of the extension
=> VSTS-369 Make cliVersion/msBuildVersion optional in pipeline yml definition

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v2/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/extensions/sonarqube/vss-extension.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-386)
- Bump the default scanner version to v6 for SQV2 and SCV6 tasks. 
- This will help mitigate the `ThrowableProxy` error due to `jGit` for SonarCloud users.
- This is a risky release (in rare cases, `sonar-scanner-cli v5 -> v6` is a breaking change (eg when the architecture can't be detected), but we released the new task versions soon, so failing now is acceptable IMO, PMs are OK with the risk as well.
Change validated on SQV6, SCV2, SQV5, SCV1
=> SONARAZDO-386 Bump sonar-scanner-cli to v6

config/utils.js
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-378)
Updates the project key on the Next projects ([SC](https://next.sonarqube.com/sonarqube/dashboard?id=org.sonarsource.scanner.vsts%3Asonar-scanner-vsts-sonarcloud), [SQ](https://next.sonarqube.com/sonarqube/dashboard?id=org.sonarsource.scanner.vsts%3Asonar-scanner-vsts))
=> SONARAZDO-378 Rename projects on Next from vsts to azdo

config/utils.js
Adding a dummy commit with code changes to this PR produces this in the summary:
Without the fix:
=> Fix SQ Next analysis

config/paths.js, config/utils.js, gulpfile.js, src/common/latest/__tests__/prepare-task-test.ts, src/common/latest/config.ts, src/common/latest/helpers/constants.ts, src/common/latest/mocks/AzureTaskLibMock.ts, src/common/latest/mocks/AzureToolLibMock.ts, src/common/latest/prepare-task.ts, src/common/latest/sonarqube/Scanner.ts, src/common/latest/sonarqube/__tests__/Scanner-test.ts, src/common/sonarcloud-v1/config.ts, src/common/sonarqube-v4/config.ts, src/common/sonarqube-v5/config.ts
- Embed default scanners in SQV6 and SCV2 tasks
- This PR alsoimplements [SONARAZDO-351](https://sonarsource.atlassian.net/browse/SONARAZDO-351) to build a mocking architecture allowing to mock AzDO variables/input directly rather than assuming the invocation order
- Change build process to support independent msbuild vs scanner cli versions
- Drop `777` permission (replaced with `500`) on scanner files (this is failing SQ scan)
[SONARAZDO-351]: https://sonarsource.atlassian.net/browse/SONARAZDO-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-385 Allow offline execution for SQV6, SCV2 tasks

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v2/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/extensions/sonarqube/vss-extension.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-393)
This release is a new major release, but the mentioned breaking change shouldn’t be one for us (change of default sonar.host.url) because we are always specifying it.
=> SONARAZDO-393 Bump embedded .NET scanner to 7.1

.github/workflows/release.yml
A fix was made to gh-action_release in https://github.com/SonarSource/gh-action_release/pull/233 to support multiple artifacts in repox (which was implemented as part of https://sonarsource.atlassian.net/browse/SONARAZDO-391)
This PR updates the release workflow to use the new version with the fix. Could you please merge this and do a release to test this? if it goes well, I will update the v5 Branch with the fix and then you can revert this PR.
=> BUILD-5506: Support multiple repox artifacts for sonar-scanner-azdo

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v2/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/extensions/sonarqube/vss-extension.json
There has to be 2 releases:
- Users will be automatically moved to this minor patch release
- The next release will be major and will need manual action on users to use the new extension and task versions
- The next release should also come with updated documentation for SQ/SC
=> SONARAZDO-395 Revert default .NET scanner version to v6 for SC V2 & SQ V6 tasks

src/common/latest/helpers/__tests__/request-test.ts, src/common/latest/helpers/request.ts, src/common/latest/package-lock.json, src/common/latest/package.json, src/common/latest/sonarqube/Endpoint.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v2/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v2/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/extensions/sonarqube/vss-extension.json
This comes from a dogfood thread / support request
We can finally upgrade to `node-fetch@3` on the Node16 tasks
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-394)
=> SONARAZDO-394 Upgrade node-fetch to v3

azure-pipelines.yml
Combined with this setting in AzDO, this change should allow having multiple QA running simultaneously (with 1 max concurrent run)
=> SONARAZDO-407 Allow more than one pull request to be open and run QA at the same time

.cirrus.yml
If a pull request bumps one of the `.vsix` file size to >30MB, the `check_size` task will fail with an error:
BTW I think the limit should be 20MB (because that's the limit for TFS Server 2018), but we currently are over this limit already.
=> SONARAZDO-397 Track extension size in pull requests

azure-pipelines.yml, gulpfile.js, src/common/latest/esbuild.config.js, src/common/latest/package-lock.json, src/common/latest/package.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-384)
This will unblock [SONARAZDO-379](https://sonarsource.atlassian.net/browse/SONARAZDO-379)
The second commit fixes a regression I introduced [in this PR](https://github.com/SonarSource/sonar-scanner-azdo/pull/409) where the QA was trying to run before the extension was installed and tasks are available
[SONARAZDO-379]: https://sonarsource.atlassian.net/browse/SONARAZDO-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-384 Make shelljs dependency usable in our task codes

gulpfile.js, src/common/latest/config.ts
PR to let .NET squad create builds including custom .NET scanners (not downloaded from GitHub).
How to use:
1. When building the extension, run:
```bash
SCANNER_NET_FRAMEWORK_LOCATION=/path/to/sonar-scanner-9.0.0-rc.99116-net-framework.zip \
SCANNER_NET_LOCATION=/path/to/sonar-scanner-9.0.0-rc.99116-net.zip \
npm run test-build -- --publisher your-publisher
```
2. Publish the test extension in under your test publisher, share it with your org then install it
3. Ensure your pipeline does NOT specify `msBuildVersion`, otherwise your embedded scanner won't be used
____
Validated after downloading [v9-rc scanner](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/9.0.0-rc.99116) and running the commands above on a Windows agent
=> NO-JIRA Allow local .NET scanner override

src/common/latest/mocks/AzureToolLibMock.ts, src/common/latest/sonarqube/Scanner.ts, src/common/latest/sonarqube/__tests__/Scanner-test.ts
https://sonarsource.atlassian.net/browse/SONARAZDO-379
Findings, azdo hosted agents are ephemeral in nature which means there is no way a task itself can persist files between runs. 
The only way Azure pipelines will persist is by defining a Cache task
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines
e.g. (probably a simpler key is possible) 
```
- task: Cache@2
inputs:
key: 'SonarScanner | "$(Build.SourcesDirectory)/src/extensions/sonarcloud" | "$(Build.SourcesDirectory)/src/extensions/sonarqube"'
path: '$(Agent.ToolsDirectory)/SonarScanner MSBuild'
cacheHitVar: 'CACHE_RESTORED'
```
These changes make it possible to check for a cached version, without it; the scanner would ignore a cache even if it was defined, and always download
=> SONARAZDO-379 Improve cache strategy for downloaded scanner

config/utils.js
For `sonar(qube|cloud)-v*` folders, should:
- Stop checking coverage
- Stop checking duplication 
- Continue finding code smells/hotspots 
It means that when we create a new major task versions, if we have debt on latest, we need to accept the issues on the `sonar(qube|cloud)-v*` folders
I validated this PR with a dummy commit that I will drop after your review
=> NO-JIRA Fix AzDO quality gate to ignore code coverage on non-latest SQ/SC common folders

.cirrus.yml, its/Models/DotnetCoreV3TestCase.cs, its/Models/DotnetFrameworkV3TestCase.cs, src/common/latest/config.ts, src/common/sonarcloud-v2/config.ts, src/common/sonarqube-v6/config.ts
- https://sonarsource.atlassian.net/browse/SONARAZDO-396
- https://sonarsource.atlassian.net/browse/SONARAZDO-410
This bumps the extension size from `24M` to `37M`, because:
- The Scanner CLI size was bumped from `4.7M` to `13M` (due to [this commit](https://github.com/SonarSource/sonar-scanner-cli/commit/8ef04a5f85ae29d14a1bfe4c930ab81e096e5456))
- The Scanner for .NET size was bumped from `2.3M`to `2.6M`
=> SONARAZDO-396 Include new Scanner .NET v9 in SQ/SC extensions & Bump the embedded Scanner CLI version to v6.2.1

src/common/latest/helpers/html.ts, src/common/latest/sonarqube/__tests__/__snapshots__/HtmlAnalysisReport-test.ts.snap
[SONARAZDO-358](https://sonarsource.atlassian.net/browse/SONARAZDO-358)
This simply drops the hardcoded color styling we added on the container div
Screenshots
[SONARAZDO-358]: https://sonarsource.atlassian.net/browse/SONARAZDO-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-358 Fix Azure PR decoration in dark themes

.github/workflows/release.yml
To notify the new `azdo` channel rather than the previous unused one
=> NO-JIRA Update release notification channel

.cirrus.yml
I think a simple solution like this is enough to ensure the generate pipelines are always up to date 
If there was an uncommitted change to the generates pipelines, the Cirrus build fails and shows the diff
=> SONARAZDO-416 Use snapshot-based testing to ensure generated pipelines did not unexpectedly changed without being committed

azure-pipelines.yml, its/it/azdo.ts, its/it/cases.ts, its/it/runner.ts, its/it/sonar.ts
Leverages hosted runners concurrency to speed up our pipeline. Tasks are parallelized per project key.
For now, it drops the pipeline total time from `~29min` to `~17.5min`, but this change means that if we add some tests for the CLI Scanner or Maven, Gradle, the pipeline wouldn't take longer, because the longest pipelines are the .net framework ones at the moment (there are 3 of them)
A second commit drops the `validate-ci` check from the Azure pipeline (it's already run in the Cirrus build). This saves almost 3min from the full QA run.
Execution plan as of now:
```text
Execution plan: 
pipeline-sonarcloud-v3-dotnet-8.0.3.99785-windows,pipeline-sonarcloud-v3-dotnet-embedded-windows,pipeline-sonarcloud-v2-dotnet-embedded-windows
pipeline-sonarcloud-v3-dotnet-8.0.3.99785-unix,pipeline-sonar …
```
=> SONARAZDO-416 Parallelize IT pipelines

gulpfile.js
Always bump the test extension version to `10.0.0.{buildNumber}` to avoid conflicts when we bump minor/patch versions. `10` is an arbitrary choice (it works for me because I already uploaded up to version `8` locally.
=> SONARAZDO-439 Fix CI extension version bumps

azure-pipelines.yml
The dogfood extension shouldn't have its tasks suffixed with `Test`
Previous flow of actions:
1. Hotfix task/extension versions
2. Hotfix task names (suffix with `Test`)
3. Build extension in `/a`
4. During publish step, use the same vsix for the dogfood and test
New flow of action:
1. Hotfix task/extension versions
5. Build dogfood extension in `extensions/dogfood`
6. Hotfix task names (suffix with `Test`)
7. Build test extension in `extensions/test`
8. During publish step, go and fetch the 2 built extensions
=> NO-JIRA Fix dogfooding extension published

src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v3/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v7/task.json, src/extensions/sonarqube/vss-extension.json
- Bump latest SonarQube Server extension versions to `7.1.0`
- Bump latest SonarQube Cloud extension versions to `3.1.0`
So that users get the rebranded extension/tasks
=> NO-JIRA Bump latest extension/task versions to 3.1.0 (SQC) and 7.1.0 (SQS)

src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-440)
What this PR changes is that the RAW value of `cliSources` is now used instead of the converted value to an absolute path:
vs
Assuming a repository structure like this:
```text
- docs-src/src/components
```
With this setup:
```yml
- task: SonarCloudPrepare@3
inputs:
[..]
cliSources: src\components
extraProperties: |
sonar.projectBaseDir=$(Build.SourcesDirectory)\docs-src
```
The value of `cliSources` is changed before it is setn to the task to be an absolute path starting from the repository root (not `projectBaseDir`). Therefore the analysis fails
With this fix, with the same task definition, we can see the results on SonarQube Cloud which is as expected
=> SONARAZDO-440 Forward the cliSources input as intended to the CLI Scanner

src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/vss-extension.json
Marketplace pages:
- https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud
- https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube
Current backgrounds
Problem
- SonarQube Cloud extension should use a background color from the rebranded color palette (N2: `rgb(244, 247, 251)`)
- SonarQube Server extension should use a light background with the new background color `N2` as well
=> SONARAZDO-444 Fix marketplace title background color to match rebranded logos

.cirrus/Dockerfile, azure-pipelines.yml
Both the Cirrus and Azure DevOps QA are failing, but for different reasons. Justifications are in [SONARAZDO-446](https://sonarsource.atlassian.net/browse/SONARAZDO-446).
Failing pipelines:
- [Azure DevOps](https://dev.azure.com/sonarsource/SonarScannerAzdo/_build/results?buildId=108453&view=logs&j=f1338668-1e5b-508a-0652-45679475677e&t=2f3fd90c-e401-5d08-e0c9-5abd54dad81f&l=64)
- [Cirrus CI](https://cirrus-ci.com/task/5768958130782208?logs=build#L160)
Commits:
- [Fix the Azure DevOps CI by pinning NPM version to 11](https://github.com/SonarSource/sonar-scanner-azdo/pull/457/commits/c3398be6d9fe6ec383fce5c8348cbf250f0eb57c)
- [Rely on APT to install NodeJS 18](https://github.com/SonarSource/sonar-scanner-azdo/pull/457/commits/374008cbaa87e56c081dc10f818848ffa7c120bd)
[SONARAZDO-446]: …
=> SONARAZDO-446 Fix Azure DevOps & Cirrus CI QA

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v3/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v7/task.json, src/extensions/sonarqube/vss-extension.json
[SONARAZDO-458](https://sonarsource.atlassian.net/browse/SONARAZDO-458)
AzDevops extensions also need a version bump as in #426
[SONARAZDO-458]: https://sonarsource.atlassian.net/browse/SONARAZDO-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-458 Bump Scanner for .NET 10.1.0.110937

src/common/latest/helpers/__tests__/request-test.ts, src/common/latest/helpers/constants.ts, src/common/latest/helpers/utils.ts, src/common/latest/sonarqube/Endpoint.ts, src/common/latest/sonarqube/__tests__/Endpoint-test.ts
[SONARAZDO-465](https://sonarsource.atlassian.net/browse/SONARAZDO-465)
We can't do it for SonarQube Server as older versions were only supporting passing the token through BASIC authentication.
[SONARAZDO-465]: https://sonarsource.atlassian.net/browse/SONARAZDO-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-465 Use Bearer authentication for Axios when contacting SonarQube Cloud

.cirrus.yml, gulpfile.js, src/common/sonarcloud-v1/jest.config.js, src/common/sonarqube-v5/jest.config.js
[SONARAZDO-469](https://sonarsource.atlassian.net/browse/SONARAZDO-469)
[SONARAZDO-469]: https://sonarsource.atlassian.net/browse/SONARAZDO-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-469 Fix the coverage measurement
