common/ts/sonarqube/Scanner.ts, config/config.js, config/paths.js, gulpfile.js
Fixes https://jira.sonarsource.com/browse/VSTS-145
Fixes https://jira.sonarsource.com/browse/VSTS-146
=> Embed Dotnet Scanner for MSBuild (4.1.0.1148)

.gitignore, extensions/sonarcloud/templates/gradle/template.json, extensions/sonarcloud/templates/maven/template.json, extensions/sonarcloud/templates/netcore/template.json, extensions/sonarcloud/templates/netdesktop/template.json, extensions/sonarcloud/vss-extension.json, gulpfile.js
Fixed [VSTS-128](https://jira.sonarsource.com/browse/VSTS-128)
=> Added build templates

.eslintignore, .travis.yml, common/ts/helpers/__tests__/utils-test.ts, common/ts/helpers/utils.ts, common/ts/package-lock.json, common/ts/package.json, common/ts/prepare-task.ts, common/ts/publish-task.ts, common/ts/sonarqube/Analysis.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/Scanner.ts, common/ts/sonarqube/Task.ts, common/ts/sonarqube/TaskReport.ts, common/ts/sonarqube/__tests__/Analysis-test.ts, common/ts/sonarqube/__tests__/Endpoint-test.ts, common/ts/sonarqube/__tests__/__snapshots__/Analysis-test.ts.snap, config/paths.js, config/utils.js, gulpfile.js, package-lock.json, package.json, tsconfig.json
Copy of PR https://github.com/SonarSource/sonar-scanner-vsts/pull/30
=> Allow Multiple Scans To Be Published

extensions/sonarcloud/overview.md, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/overview.md, extensions/sonarqube/vss-extension.json
Updating overview and markdown descriptions for both sq/sc extensions.
=> VSTS-160 - Update Marketplace descriptions to fit product positioning

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Embed Scanner for MSBuild 4.4.2.1543

common/ts/prepare-task.ts
Tested using TFS 2018 Update 2 and SonarQube 7.2.1
=> Adding github enterprise provider

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/tasks/publish/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/tasks/publish/new/task.json, extensions/sonarqube/tasks/scanner-cli/old/task.json, extensions/sonarqube/vss-extension.json
Fixed https://jira.sonarsource.com/browse/VSTS-182 - embed scanner v 4.6.0.1930
=> Update scanner and version numbers

common/ts/__tests__/publish-task-test.ts, common/ts/publish-task.ts, common/ts/sonarqube/__tests__/TaskReport-test.ts
Fixed #169
Miscellaneous:
* refactored the publish-task to make it easier to test
* add test coverage for publish-task
=> VSTS-169 Show project name in QG build status summary

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/tasks/publish/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/tasks/publish/new/task.json, extensions/sonarqube/vss-extension.json
Updated embedded S4MSB version to 4.6.2.2108
=> Fix - Updated versions

extensions/sonarqube/overview.md
=> Add warning regarding use with VSTS MMS-30

common/ts/__tests__/prepare-task-test.ts, common/ts/package-lock.json, common/ts/package.json, common/ts/prepare-task.ts, common/ts/sonarqube/TaskReport.ts, common/ts/sonarqube/__tests__/TaskReport-test.ts
…and thus the directory to get report from for uploading summaries) + updated UT
=> VSTS-190 Changed the directory for generating report-task.txt files

.eslintignore, common/ts/helpers/temp-find-method.ts, common/ts/sonarqube/TaskReport.ts, common/ts/sonarqube/__tests__/TaskReport-test.ts, config/utils.js
As discussed in the JIRA ticket, and as long as we are waiting for the fix on the lib side, both find and findMatch methods have been embedded to workaround the issue with the GC size limit exceeded.
=> VSTS-172 - workaround with embedded find method

config/config.js
Scanner CLI : 4.1.0.1829 
S4MSB : 4.7.1.2311
=> VSTS-204 - Updated embedded Scanner CLI  and Scanner for MSBuild versions 

config/config.js, extensions/sonarcloud/templates/otherfile/template.json, extensions/sonarcloud/templates/othermanual/template.json, extensions/sonarcloud/vss-extension.json, package.json
- file and manual, with only Prepare Analysis, Run Code Analysis and Publish Quality Gate Result (disabled) tasks. + Bumped S4MSB version to 4.7.0
=> VSTS-215 - Added templates for both mode of using Scanner CLI

common/ts/helpers/__tests__/azdo-api-utils-test.ts, common/ts/helpers/azdo-api-utils.ts, common/ts/prepare-task.ts
at least to not fail the whole task if any error occured.
=> VSTS-220 - Making call to AzDo (build property) optional

extensions/sonarcloud/vss-extension.json
Point to link on Azure DevOps Labs
=> Point to link on Azure DevOps Labs

extensions/sonarcloud/vss-extension.json, extensions/sonarqube/vss-extension.json
=> VSTS-225 - Added privacy policy in both extensions manifest

extensions/sonarqube/overview.md
Change commercial edition link to point at new DE/EE promotion page.
=> Update link to DE/EE MMS-96

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/tasks/scanner-cli/old/task.json, extensions/sonarqube/vss-extension.json
S4MSB : 4.9.0.17385
ScannerCLI : 4.3.0.2102 + Bumped extension versions.
=> VSTS-227 - Bumped version of S4MSB + ScannerCLI

common/ts/__tests__/prepare-task-test.ts, common/ts/__tests__/publish-task-test.ts, common/ts/analyze-task.ts, common/ts/helpers/__tests__/azdo-api-utils-test.ts, common/ts/helpers/azdo-api-utils.ts, common/ts/helpers/azdo-server-utils.ts, common/ts/helpers/measures.ts, common/ts/helpers/request.ts, common/ts/helpers/temp-find-method.ts, common/ts/helpers/utils.ts, common/ts/prepare-task.ts, common/ts/publish-task.ts, common/ts/sonarqube/Analysis.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/Metrics.ts, common/ts/sonarqube/Scanner.ts, common/ts/sonarqube/Task.ts, common/ts/sonarqube/TaskReport.ts, common/ts/sonarqube/__tests__/Analysis-test.ts, common/ts/sonarqube/__tests__/Endpoint-test.ts, common/ts/sonarqube/__tests__/TaskReport-test.ts, extensions/sonarcloud/tasks/analyze/new/analyze.ts, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/vss-extension.json, package-lock.json, package.json
=> VSTS-232 handle Java warning as a build warning, as part of MMF-2035

common/ts/analyze-task.ts, common/ts/helpers/java-version-resolver.ts
=> VSTS-235 If available, use JAVA_HOME_11_X64 as JAVA_HOME

extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/vss-extension.json
=> Update SC extension version to 1.13, as well as the analyze task.

common/ts/helpers/__tests__/utils-test.ts, common/ts/helpers/utils.ts, common/ts/sonarqube/Scanner.ts, config/config.js
=> VSTS-238 Pass the name/version of the Scanner with the new --from flag.

common/ts/helpers/__tests__/utils-test.ts, common/ts/helpers/utils.ts, common/ts/sonarqube/Scanner.ts
=> VSTS-239 Revert Scanner CLI identity

extensions/sonarcloud/overview.md, extensions/sonarcloud/tasks/prepare/new/task.json
=> VSTS-233 small doc fixes

extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/vss-extension.json
=> Bumped version for SonarCloud ext to 1.15

common/ts/__tests__/publish-task-test.ts, common/ts/publish-task.ts, common/ts/sonarqube/Analysis.ts, common/ts/sonarqube/Task.ts, common/ts/sonarqube/__tests__/Analysis-test.ts, extensions/sonarcloud/tasks/publish/new/task.json, extensions/sonarcloud/vss-extension.json, package-lock.json
=> SC-2556 Show warning on pipeline quality gate

common/ts/sonarqube/Task.ts
=> SC-2556 Do not log useless warning

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-242 - Bumped SonarScanner for .NET version 5.0.0 + extension versions.

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/SonarQubePreBuildImpl.ps1, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Revert version to S4MSB 4.10

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Bump SonarScanner for .NET to version 5.0.2.23773 + extension versions

config/config.js, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Rollback SonarScanner for MSBuild version for SQ.

config/config.js, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Bump SonarScanner for .NET to version 5.0.3 + extension versions

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Bump SonarScanner for .NET 5.0.4 + extension versions

extensions/sonarcloud/tasks/publish/new/task.json, extensions/sonarcloud/vss-extension.json
=> Bump PublishQG task version

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-251 Bump SonarScannr for .NET version (5.1.0) + extension versions

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Bump S4NET to 5.2.0.29862 and extension versions.

common/ts/helpers/utils.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/__tests__/Endpoint-test.ts
=> Do not pass sonar.password if it's empty.

.cirrus.yml, cirrus/Dockerfile, common/ts/helpers/utils.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/__tests__/Endpoint-test.ts
=> Use SQ GCP project

.cirrus.yml, cirrus/Dockerfile, common/ts/helpers/utils.ts, common/ts/sonarqube/Endpoint.ts, common/ts/sonarqube/__tests__/Endpoint-test.ts, config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/tasks/scanner-cli/old/task.json, extensions/sonarqube/vss-extension.json
=> New Release : SQ-4.20.0 ; SC-1.23.0

extensions/sonarcloud/tasks/analyze/new/package.json, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/analyze/old/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/prepare/old/task.json, extensions/sonarqube/vss-extension.json
=> Bumped S4NET to v5.2.2

config/config.js, extensions/sonarcloud/tasks/analyze/new/task.json, extensions/sonarcloud/tasks/prepare/new/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-230 Ship .NET Core 3 version instead of 2 for Scanner for .NET

.cirrus.yml
=> Fix sonar token for next

common/ts/package-lock.json, common/ts/package.json, common/ts/sonarqube/Task.ts, extensions/sonarcloud/tasks/analyze/new/package-lock.json, extensions/sonarcloud/tasks/prepare/new/package-lock.json, extensions/sonarcloud/tasks/publish/new/package-lock.json, extensions/sonarqube/tasks/analyze/new/package-lock.json, extensions/sonarqube/tasks/analyze/new/package.json, extensions/sonarqube/tasks/analyze/new/task.json, extensions/sonarqube/tasks/prepare/new/package-lock.json, extensions/sonarqube/tasks/prepare/new/package.json, extensions/sonarqube/tasks/prepare/new/task.json, extensions/sonarqube/tasks/publish/new/package-lock.json, extensions/sonarqube/tasks/publish/new/package.json, extensions/sonarqube/tasks/publish/new/task.json, extensions/sonarqube/vss-extension.json, package.json
=> Rollback changes to Node handler and az pipeline task lib.

config/config.js
=> VSTS-264 Bump SonarScanner for .NET to 5.4.0.40033

common/ts/prepare-task.ts, commonv5/ts/prepare-task.ts, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> Revert removal of login

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json, package-lock.json
=> VSTS-267 Bump SonarScanner for .NET to 5.4.1.41282

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-269 Bumped Scanner for .NET to 5.5.0.42949

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-270 Revert Scanner for .NET to 5.4.1.41282

common/ts/helpers/__tests__/azdo-api-utils-test.ts, commonv5/ts/helpers/__tests__/azdo-api-utils-test.ts
=> VSTS-271 fix unit tests

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-273 Bumped SonarScanner for .NET 5.5.3.43281

extensions/sonarcloud/overview.md, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json
=> VSTS-277 Update documentation links

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-280 Bump Scanner for .NET to 5.6.0.48455

docs/PULL_REQUEST_TEMPLATE.md
=> Fix link in PR template to point to contributing.md (try 2)

azp/helpers.ps1, azure-pipelines.yml, config/utils.js, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/vss-extension.json, gulpfile.js
=> Merge build infos + remove SNAPSHOT support

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-285 Revert Scanner for .NET to 5.6.0.48455 and ScannerCLi to 4.6.2.2472

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-287 Bumped S4NET to 5.8.0.52797

common/ts/sonarqube/Task.ts, commonv5/ts/sonarqube/Task.ts, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/publish/v4/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-288 Fix spelling for CANCELED status on api/ce/task

extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json
=> VSTS-289 Update CI based analysis azure documentation link

config/config.js, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v4/task.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v4/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-293 Bump Scanner for .NET version to 5.9.2.58699

azure-pipelines.yml
=> Temporary deactivate E2E tests on short living branches

commonv5/ts/helpers/azdo-api-utils.ts, commonv5/ts/prepare-task.ts, commonv5/ts/sonarqube/TaskReport.ts, commonv5/ts/sonarqube/__tests__/TaskReport-test.ts
=> Allow sonar scanner metadata file path property usage

commonv5/ts/__tests__/prepare-task-test.ts, commonv5/ts/analyze-task.ts, commonv5/ts/helpers/utils.ts, commonv5/ts/prepare-task.ts, commonv5/ts/sonarqube/Endpoint.ts, commonv5/ts/sonarqube/__tests__/Endpoint-test.ts
=> VSTS-302 Use sonar.token instead of sonar.login for SQ >= 10.0

common/ts/analyze-task.ts, commonv5/ts/__tests__/analyze-task-test.ts, commonv5/ts/analyze-task.ts, commonv5/ts/helpers/__tests__/java-version-resolver-test.ts, commonv5/ts/helpers/java-version-resolver.ts, extensions/sonarcloud/tasks/analyze/v1/analyze.ts, extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/analyze.ts, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
=> VSTS-307 Users can decide which Java version they want for analysis

.cirrus.yml, wss-unified-agent.config
=> VSTS-304 Add Mend task

extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
=> SC-9758 Bump extensions version

extensions/sonarcloud/overview.md
=> Update UTM links

config/config.js
[Tracking JIRA ticket](https://sonarsource.atlassian.net/browse/VSTS-318)
=> VSTS-318 Bump MSBuild scanner to 5.14.x

extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json, extensions/sonarqube/tasks/analyze/v5/task.json, extensions/sonarqube/tasks/prepare/v5/task.json, extensions/sonarqube/tasks/publish/v5/task.json, extensions/sonarqube/vss-extension.json
=> [NO-JIRA] Bump task version

extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json
Brings our latest fix to SonarCloud 1.44.1
See https://github.com/SonarSource/sonar-scanner-vsts/pull/299
=> VSTS-322 Bump SonarCloud task and extension version

commonv5/ts/__tests__/publish-task-test.ts, commonv5/ts/publish-task.ts, commonv5/ts/sonarqube/Analysis.ts, commonv5/ts/sonarqube/__tests__/Analysis-test.ts, commonv5/ts/sonarqube/__tests__/__snapshots__/Analysis-test.ts.snap, commonv5/ts/sonarqube/__tests__/utils-test.ts, commonv5/ts/sonarqube/types.ts, commonv5/ts/sonarqube/utils.ts
Not to reviewer:
QA is failing with:
```
Failed Execute_Build_And_Analysis(IntegrationTests.Models.CobolTestCase) [1 m 22 s]
Error Message:
Expected: 2754
But was:  2907
```
I think this is caused by another recent change to SC scanner, I opened [another PR](https://github.com/SonarSource/sonar-scanner-vsts/pull/327) with a dummy change to confirm
=> VSTS-344 Refactor HTML generation logic

extensions/sonarcloud/tasks/analyze/v1/task.json, extensions/sonarcloud/tasks/prepare/v1/task.json, extensions/sonarcloud/tasks/publish/v1/task.json, extensions/sonarcloud/vss-extension.json
=> [NO-JIRA] Bump SC extension task versions

common/ts/package-lock.json, common/ts/package.json, commonv5/ts/package-lock.json, commonv5/ts/package.json, extensions/sonarcloud/tasks/analyze/v1/package-lock.json, extensions/sonarcloud/tasks/analyze/v1/package.json, extensions/sonarcloud/tasks/prepare/v1/package-lock.json, extensions/sonarcloud/tasks/prepare/v1/package.json, extensions/sonarcloud/tasks/publish/v1/package-lock.json, extensions/sonarcloud/tasks/publish/v1/package.json, extensions/sonarqube/tasks/analyze/v4/package-lock.json, extensions/sonarqube/tasks/analyze/v4/package.json, extensions/sonarqube/tasks/analyze/v5/package-lock.json, extensions/sonarqube/tasks/analyze/v5/package.json, extensions/sonarqube/tasks/prepare/v4/package-lock.json, extensions/sonarqube/tasks/prepare/v4/package.json, extensions/sonarqube/tasks/prepare/v5/package-lock.json, extensions/sonarqube/tasks/prepare/v5/package.json, extensions/sonarqube/tasks/publish/v4/package-lock.json, extensions/sonarqube/tasks/publish/v4/package.json, extensions/sonarqube/tasks/publish/v5/package-lock.json, extensions/sonarqube/tasks/publish/v5/package.json, package-lock.json, package.json
This fixes [the mend vuln](https://saas-eu.whitesourcesoftware.com/Wss/WSS.html#!libraryDetails;uuid=d34620e1-997b-4cf4-9d8c-7d38828d3174;product=302848;orgToken=b55a9158-7eca-400e-809d-5d5f0a5ea7df) on this project
=> NO-JIRA Fix mend vulnerability

sonar-docs/analysis/scan/sonarscanner-for-azure-devops.md, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v4/task.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v5/task.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v4/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v5/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v6/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v4/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v5/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v6/task.json, src/extensions/sonarqube/vss-extension.json, yaml-pipeline-templates/generic-analysis-properties-file-sonarcloud.yml, yaml-pipeline-templates/maven-sonarcloud.yml
Simple PR, updating links
[ticket](https://sonarsource.atlassian.net/browse/VSTS-359)
=> VSTS-359 Update outdated links in documentation, tasks and extension definitions

src/common/sonarcloud-v1/analyze-task.ts, src/common/sonarcloud-v1/helpers/constants.ts, src/common/sonarcloud-v1/prepare-task.ts, src/common/sonarcloud-v1/publish-task.ts, src/common/sonarqube-v5/analyze-task.ts, src/common/sonarqube-v5/helpers/constants.ts, src/common/sonarqube-v5/prepare-task.ts, src/common/sonarqube-v5/publish-task.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v1/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v1/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v1/task.json, src/extensions/sonarcloud/tasks/SonarCloudQualityGateCheck/v1/task.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v4/task.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v5/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v4/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v5/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v4/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v5/task.json
=> VSTS-382 Deprecate SC v1 and SQ v5 tasks

src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/vss-extension.json
=> NO-JIRA bump patch version on the extensions

config/utils.js, gulpfile.js
details in [the ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-391)
This PR splits the artifacts into 2 different projects on Repox
- https://repox.jfrog.io/ui/builds/sonar-scanner-azdo-sc/?buildRepo=artifactory-build-info
- https://repox.jfrog.io/ui/builds/sonar-scanner-azdo-sq/?buildRepo=artifactory-build-info
The release pipelines (Azure) should also be updated to support this.
=> SONARAZDO-391 Split the artifacts into two different projects

package-lock.json, package.json, src/common/latest/package-lock.json, src/common/latest/package.json, src/common/sonarcloud-v1/package-lock.json, src/common/sonarcloud-v1/package.json, src/common/sonarqube-v4/package-lock.json, src/common/sonarqube-v4/package.json, src/common/sonarqube-v5/package-lock.json, src/common/sonarqube-v5/package.json
See [ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-399) for details
Validated with old tasks (SQ V5, SQ V4, SC V1)
=> SONARAZDO-399 Upgrade semver to v7

config/utils.js, src/common/latest/__tests__/analyze-task-test.ts, src/common/latest/__tests__/prepare-task-test.ts, src/common/latest/__tests__/publish-task-test.ts, src/common/latest/__tests__/setup.ts, src/common/latest/helpers/__tests__/api-test.ts, src/common/latest/helpers/__tests__/azdo-api-utils-test.ts, src/common/latest/helpers/__tests__/java-version-resolver-test.ts, src/common/latest/helpers/__tests__/logging-test.ts, src/common/latest/helpers/__tests__/request-test.ts, src/common/latest/helpers/api.ts, src/common/latest/helpers/azdo-api-utils.ts, src/common/latest/helpers/azdo-server-utils.ts, src/common/latest/helpers/java-version-resolver.ts, src/common/latest/helpers/logging.ts, src/common/latest/helpers/request.ts, src/common/latest/jest.config.js, src/common/latest/mocks/AzureTaskLibMock.ts, src/common/latest/mocks/helpers.ts, src/common/latest/prepare-task.ts, src/common/latest/publish-task.ts, src/common/latest/run.ts, src/common/latest/sonarqube/Endpoint.ts, src/common/latest/sonarqube/HtmlAnalysisReport.ts, src/common/latest/sonarqube/Scanner.ts, src/common/latest/sonarqube/Task.ts, src/common/latest/sonarqube/TaskReport.ts, src/common/latest/sonarqube/__tests__/Task-test.ts, src/common/latest/sonarqube/__tests__/TaskReport-test.ts
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-406)
- There is little functional impact (some log type are changed from debug to info, or from/to warnings/errors). Functional changes are highlighted below.
- Due to the logging changes, the initial coverage was very low. I added a few unit tests to improve the coverage for this PR.
=> SONARAZDO-406 Fix confusing log messages & Introduce INFO logs

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v3/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v7/task.json, src/extensions/sonarqube/vss-extension.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-420)
UNIX (.NET Core)
<details>
</details>
Windows (.NET Framework)
<details>
</details>
=> SONARAZDO-420 Bump Sonar Scanner for .NET version to 9.0.1.102776

azure-pipelines.yml
=> SONARAZDO-424 Run full QA on nightly master

azure-pipelines.yml
=> NO-JIRA Update azdo task versions

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v3/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v7/task.json, src/extensions/sonarqube/vss-extension.json
[ticket](https://sonarsource.atlassian.net/browse/SONARAZDO-441)
[release](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/9.0.2.104486)
=> SONARAZDO-441 Bump Scanner for .NET 9.0.2.104486

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[SONARAZDO-445](https://sonarsource.atlassian.net/browse/SONARAZDO-445)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last …
=> SONARAZDO-445 Add Jira integration

package-lock.json, src/common/latest/package-lock.json, src/common/latest/package.json
[SONARAZDO-459](https://sonarsource.atlassian.net/browse/SONARAZDO-459)
Fixing vulnerabilities on:
* axios 1.7.7: upgrade to 1.8.2
* @babel/runtime and @babel/helpers: upgrade @babel/preset-env to 7.26.9, @babel/core to 7.26.10 and @babel/runtime to 7.26.10
And please ensure your pull request adheres to the following guidelines: 
- Provide a unit test for any code you changed
[SONARAZDO-459]: https://sonarsource.atlassian.net/browse/SONARAZDO-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-459 Fix Mend vulnerabilities

package-lock.json, package.json
[SONARAZDO-459](https://sonarsource.atlassian.net/browse/SONARAZDO-459)
[SONARAZDO-459]: https://sonarsource.atlassian.net/browse/SONARAZDO-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-459 Fix more Mend vulnerabilities

azure-pipelines.yml
[SONARAZDO-462](https://sonarsource.atlassian.net/browse/SONARAZDO-462)
[SONARAZDO-462]: https://sonarsource.atlassian.net/browse/SONARAZDO-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-462 Change lock mode to sequential

src/extensions/sonarcloud/vss-extension.json
[SONARAZDO-461](https://sonarsource.atlassian.net/browse/SONARAZDO-461)
[SONARAZDO-461]: https://sonarsource.atlassian.net/browse/SONARAZDO-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-461 Use Bearer scheme to validate the token

scripts/install.sh, src/common/sonarcloud-v1/package-lock.json, src/common/sonarcloud-v1/package.json, src/common/sonarcloud-v2/package-lock.json, src/common/sonarcloud-v2/package.json, src/common/sonarqube-v5/package-lock.json, src/common/sonarqube-v5/package.json, src/common/sonarqube-v6/package-lock.json, src/common/sonarqube-v6/package.json
[SONARAZDO-464](https://sonarsource.atlassian.net/browse/SONARAZDO-464)
And please ensure your pull request adheres to the following guidelines: 
[SONARAZDO-464]: https://sonarsource.atlassian.net/browse/SONARAZDO-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-464 Bump azure-pipelines-task-lib versions to 4.17.3 to run on Windows

azure-pipelines.yml, src/common/latest/config.ts, src/common/sonarcloud-v2/config.ts, src/common/sonarqube-v6/config.ts
[SONARAZDO-460](https://sonarsource.atlassian.net/browse/SONARAZDO-460)
[SONARAZDO-460]: https://sonarsource.atlassian.net/browse/SONARAZDO-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-460 Update ScannerCLI to 7.1

src/extensions/sonarcloud/vss-extension.json
[SONARAZDO-454](https://sonarsource.atlassian.net/browse/SONARAZDO-454)
[SONARAZDO-454]: https://sonarsource.atlassian.net/browse/SONARAZDO-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-454 Add a combo to select the SonarQube Cloud region

azure-pipelines.yml
[SONARAZDO-466](https://sonarsource.atlassian.net/browse/SONARAZDO-466)
SONARAZDO-462
[SONARAZDO-466]: https://sonarsource.atlassian.net/browse/SONARAZDO-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-466 Fix publish Dogfood

azure-pipelines.yml
[SONARAZDO-467](https://sonarsource.atlassian.net/browse/SONARAZDO-467)
[SONARAZDO-467]: https://sonarsource.atlassian.net/browse/SONARAZDO-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-467 Publish SonarQube Server Dogfood extension

src/extensions/sonarqube/vss-extension.json
[SONARAZDO-468](https://sonarsource.atlassian.net/browse/SONARAZDO-468)
[SONARAZDO-468]: https://sonarsource.atlassian.net/browse/SONARAZDO-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-468 Fix deprecated categorie for SonarQube Server extension

src/common/latest/config.ts, src/extensions/sonarcloud/tasks/SonarCloudAnalyze/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPrepare/v3/task.json, src/extensions/sonarcloud/tasks/SonarCloudPublish/v3/task.json, src/extensions/sonarcloud/vss-extension.json, src/extensions/sonarqube/tasks/SonarQubeAnalyze/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePrepare/v7/task.json, src/extensions/sonarqube/tasks/SonarQubePublish/v7/task.json, src/extensions/sonarqube/vss-extension.json
[SONARAZDO-470](https://sonarsource.atlassian.net/browse/SONARAZDO-470)
[SONARAZDO-470]: https://sonarsource.atlassian.net/browse/SONARAZDO-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-470 Bump Scanner for .NET 10.1.2.114627

package-lock.json, package.json
[SONARAZDO-471](https://sonarsource.atlassian.net/browse/SONARAZDO-471)
And please ensure your pull request adheres to the following guidelines: 
[SONARAZDO-471]: https://sonarsource.atlassian.net/browse/SONARAZDO-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-471 Upgrade openpgp to 5.11.3

config/utils.js, gulpfile.js
[SONARAZDO-482](https://sonarsource.atlassian.net/browse/SONARAZDO-482)
[SONARAZDO-482]: https://sonarsource.atlassian.net/browse/SONARAZDO-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-482 Always pass forward slashes to glob

src/common/latest/sonarqube/Scanner.ts
[SONARAZDO-448](https://sonarsource.atlassian.net/browse/SONARAZDO-448)
[SONARAZDO-448]: https://sonarsource.atlassian.net/browse/SONARAZDO-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARAZDO-448 Add Picked up JAVA_TOOL_OPTION error log to whitelist
